/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  experimental: {
    // Static pages are generated by one worker instead of one per CPU core.
    // Keeps peak memory low so `next build` also succeeds on 8 GB machines
    // (the site is a handful of static pages — the speed difference is tiny).
    cpus: 1,
  },
};

module.exports = nextConfig;
